# Permalinks
permalink:           pretty

# Setup
title:               S.Dasgupta
tagline:             Big Data Energy  
url:                 http://sodas32.github.io
paginate:            2
baseurl:             https://github.com/sodas32

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sonali Dasgupta
  url:               https://github.com/sodas32
  email:             sgdas32@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sodas32

# Gems
gems:
  

